In [111]:
import numpy as np

In [112]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [113]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [114]:
#Get Dimension
a.ndim

1

In [115]:
#Get Shape 
b.shape

(2, 3)

In [116]:
#Get Type
a.dtype

dtype('int16')

In [117]:
#Get Size
a.itemsize

2

In [118]:
#Get Total Size
a.nbytes

6

Accessing/Changing elements

In [119]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [120]:
#Get a specific element [r, c]
a[1][5]

13

In [121]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [122]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [123]:
# Getting a little fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [124]:
a[:, 2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [125]:
# 3D Example
b = np.array([[[1,2], [3,4], [5,6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [126]:
#Get specific element (work outside in)
b[0,1,1]

4

Initializing diffferent types of Arrays

In [127]:
#All 0's
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [128]:
#All 1's
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [129]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [130]:
#Any other number (full_like method)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [131]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.04740953, 0.67466068],
       [0.4424453 , 0.74520262],
       [0.51635726, 0.28987565],
       [0.84288249, 0.58668031]])

In [132]:
#Random integer values
np.random.randint(4,7, size=(3,3))

array([[5, 6, 5],
       [6, 6, 4],
       [4, 4, 4]])

In [134]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
#Repeat an array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [135]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1]=9

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### Be careful when copying arrays 

In [136]:
a = np.array([1,2,3])
b = a.copy()
b[0]=100
print(a)

[1 2 3]


###### Mathematics

In [137]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [138]:
a+2

array([3, 4, 5, 6])

In [139]:
a-2

array([-1,  0,  1,  2])

In [140]:
a*2

array([2, 4, 6, 8])

In [141]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [142]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [143]:
a ** 2

array([ 1,  4,  9, 16])

In [144]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

###### Linear Algebra

In [145]:
#Matrix Multiplication
a = np.ones((2,3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [146]:
#Find the determinant 
c = np.identity(3)
np.linalg.det(c)

1.0

###### Statistics

In [147]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
np.min(stats, axis=0)

array([1, 2, 3])

In [149]:
np.max(stats, axis=1)

array([3, 6])

In [150]:
np.sum(stats, axis = 0)

array([5, 7, 9])

### Reorganizing Arrays

In [151]:
before = np.array([[1,2,3,4],[5,6,7,8]])

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


In [152]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [153]:
# Horizontal stacks
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous 

###### Load Data from file

In [ ]:
filedata = np.genfromtext('data.txt', delimeter=',')

##### Boolean Masking and Advanced Indexing 